<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>95bce4cc-d706-4021-921e-258cc622d862</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
		<PackageReference Include="Octokit" Version="13.0.1" />
		<PackageReference Include="Scrutor" Version="7.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\GitHubPortfolio.Service\GitHubPortfolio.Service.csproj" />
	</ItemGroup>

</Project>